pre-release-replacements = [
  { file="README.md", search="split_ext = \"[0-9.]*\"", replace="split_ext = \"{{version}}\"" },
  { file="src/lib.rs", search="split_ext = \"[0-9.]*\"", replace="split_ext = \"{{version}}\"" },
  { file="src/lib.rs", search="https://docs[.]rs/split_ext/[0-9.]*", replace="https://docs.rs/split_ext/{{version}}" },
  { file="CHANGELOG.md", search="\\[Unreleased\\]", replace="[{{version}}] - {{date}}" }
]
